language: python

notifications:
  email: false

python:
  - 2.7
  - 3.2
  - 3.3
  - 3.4

matrix:
  include:
    - python: 2.7
      env:
        - TEST_PY3="false"
    - python: 3.2
      env:
        - TEST_PY3="true"
    - python: 3.3
      env:
        - TEST_PY3="true"
    - python: 3.4
      env:
        - TEST_PY3="true"


before_install:

 - sudo apt-get update
 - sudo apt-get install build-essential

install:

 - if [[ "${TEST_PY3}" == "false" ]]; then
       git clone https://github.com/orkohunter/networkx.git
       cd networkx/
       git checkout addons
       python setup.py install
       pip install Cython;
   fi

 - if [[ "${TEST_PY3}" == "true" ]]; then
       git clone https://github.com/orkohunter/networkx.git
       cd networkx/
       git checkout addons
       python setup.py install
       pip install Cython;
   fi

script:

 - if [[ "${TEST_PY3}" == "false" ]]; then
       python setup.py install;
       cd networkx/addons/metis
       nosetests;
   fi

 - if [[ "${TEST_PY3}" == "true" ]]; then
       cd networkx/addons/metis
       python setup.py install;
       nosetests;
   fi
