language: python

matrix:
  include:
    - python: 2.7
      env:
        - TEST_PY3="false"
    - python: 3.2
      env:
        - TEST_PY3="true"
    - python: 3.3
      env:
        - TEST_PY3="true"
    - python: 3.4
      env:
        - TEST_PY3="true"


before_install:

 - sudo apt-get update
 - sudo apt-get install build-essential

install:

 - if [[ "${TEST_PY3}" == "false" ]]; then
       pip install Cython;
       python setup.py install; # To install networkx-metis
       mkdir core; # For the installation of networkx core
       cd core;
       git clone https://github.com/orkohunter/networkx.git;
       cd networkx/;
       git checkout addons;
       python setup.py install;
   fi;

 - if [[ "${TEST_PY3}" == "true" ]]; then
       pip install Cython;
       python setup.py install; # To install networkx-metis
       mkdir core; # For the installation of networkx core
       cd core;
       git clone https://github.com/orkohunter/networkx.git;
       cd networkx/;
       git checkout addons;
       python setup.py install;
   fi;

script:

 - nosetests

notifications:
  email: false
